### PR TITLE
fix: removed 28 APIs

### PR DESCRIPTION
**Pull request by yoshutch**
[RFC0051779](https://support.byu.edu/change_request.do?sys_id=6c8275931b5a611090e421fa234bcb6c)

### CODE REVIEW

**Review by GaryGSC — APPROVED** [review]

**Comment by GaryGSC** [comment]
A little odd that the RFC is for deleting 28, yet there were 26 files changed. Everything deleted in this PR is supposed to be deleted according to the RFC.

**Review by GaryGSC — CHANGES_REQUESTED** [review]
The RFC says we're deleting 28, yet there are 26 files changed here. 

Some parts make sense: the RFC says to delete divvycloud-provisioning-dev, but that's not in this repo to begin with. 

Other things make me wonder: I see we're deleting BYU-Housing. That one isn't in the RFC.

Is this just a true-up? How'd we get this set of 26 file changes?

**Comment by yoshutch** [comment]
Some of those APIs were not in the repo, I'll double check

**Comment by yoshutch** [comment]
> The RFC says we're deleting 28, yet there are 26 files changed here.
> 
> Some parts make sense: the RFC says to delete divvycloud-provisioning-dev, but that's not in this repo to begin with.
> 
> Other things make me wonder: I see we're deleting BYU-Housing. That one isn't in the RFC.
> 
> Is this just a true-up? How'd we get this set of 26 file changes?

@GaryGSC Yep, the DiningHours and divvycloud-provisioning-dev APIs were already not in this repo

**Review by GaryGSC — APPROVED** [review]
Thanks for double-checking the list. 🙂

**Pull request merged**
